spring.application.name=gridweaver-iot-microgrid

spring.threads.virtual.enabled=true
iot.simulator.enabled=true

# --- KAFKA PRODUCER CONFIGURATION ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- KAFKA CONSUMER CONFIGURATION ---
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# --- KAFKA 50K THROUGHPUT OPTIMIZATIONS ---
# Wait up to 20ms to group messages together before sending
spring.kafka.producer.properties.linger.ms=20
# Maximum batch size (32KB)
spring.kafka.producer.properties.batch.size=32768
# Compress the batches to save network bandwidth
spring.kafka.producer.properties.compression.type=snappy